### ISSUE TITLE
Dragooncaves crashes servers due to missing scripts!

### ISSUE THREAD

**Issue by frendship-loost** [MSRevive/MasterSwordRebirth#102]
![image](https://user-images.githubusercontent.com/85242183/194771224-16ff1bc5-69bf-4b3c-9eac-793ab5482a46.png)

Image and title. Seeems to be missing all of the furion/dragoons scripts. I gave up after clicking through ~50 missing script errors.
This puts your server in a crash loop, as crashed.cfg auto executes. Strangely, I could not recover the server without validating the application through steamcmd again.

**Comment by greatguys1** [comment]
I suspect this has to do with the new script packer. The root folder "furion" has no scripts directly in it, only in the sub folder "dragoons". No other folder in the script source does this. I believe because of this, the "furion" folder didn't get packed.

**Comment by SaintWish** [comment]
should be fixed with this commit https://github.com/MSRevive/MasterSwordRebirth/commit/20c3d5d2ddcc843d700baf4725553b3f2e133480
