### ISSUE TITLE
Add some more MSC alpha stuff

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#104]
* ~~Charge bar sound effects and number like MSC Alpha~~
* Finish title system?
* Finish up changing glow colour.
* Add in dual wielding mechanic from the MSC alpha.

Also might be a good idea to add in the aim assist for shielding and healing, though might not be needed if we added in crosshair instead?

**Comment by BerntA** [comment]
crosshair would be nice
