### ISSUE TITLE
Leveling out of sync

### ISSUE THREAD

**Issue by SpectreAZ** [MSRevive/MasterSwordRebirth#117]
While testing leveling up the Pole Arms skill, I noticed it was leveling way out of sync for some reason. Does not seem to be allocating a lot of points into the Balance Column and is only focusing on Proficiency and Power. Did not see this happen with any of the other perks I was leveling, seems like some kind of bug. 

![Pole Arms 1](https://user-images.githubusercontent.com/105747989/201565725-57ac21bd-eff2-4528-8fc4-dd0c68f78bb7.jpg)
![Pole Arms 2](https://user-images.githubusercontent.com/105747989/201565737-1a1bbf07-9df2-422c-ba82-229ee11915ec.jpg)

**Comment by greatguys1** [comment]
This tends to happen a lot. XP is randomly assigned a substat when its granted which will lead to situations like this. Currently, substats are not used in any meaningful way, even with natural stat (strength, agility, etc...) calculations. It may be safe to remove substats, except in spellcasting, to prevent this behavior. We will have to see what approach we take though.

**Comment by SaintWish** [comment]
Yeah we've been discussing what to do about the experience system, but we don't know what to do yet.
