### ISSUE TITLE
Replace sound engine if possible

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#131]
Currently Goldsrc uses a old version of fmod, but it might be possible to upgrade to OpenAL which would give us OGG and FLAC sound format support. This would also give us hardware acceleration among some other stuff.

Going off of this repo https://github.com/LAGonauta/MetaAudio which uses Metamod so it might take a bit of work to get something similar with our game since we don't want to rely on the use of Metamod.

**Comment by BerntA** [comment]
We could update FMOD to a newer version too, I have version 4.44.45 on my drive
it has support for ogg, flac and more: https://documentation.help/FMOD-Ex/introduction.html

**Comment by SaintWish** [comment]
Yeah that would probably be way better than replacing it with a new sound engine. I forgot FMOD still exists lol

**Comment by PHILLIPGATLIN** [comment]
How many musical tracks can be played simultaneously with fmod?

**Comment by BerntA** [comment]
the amount of channels can be defined, though, why would you want to play multiple music soundtracks at the same time??
