### ISSUE TITLE
Disable player collision at spawn

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#133]
Or just disable it completely?

**Comment by Tsarenir** [comment]
would be sweet to make melee easier in populated servers, plus using non-tork bows at all, but it would need a way make boosting still possible

**Comment by Dridje** [comment]
Summon chair spell

**Comment by Dridje** [comment]
But serious answer, that's something you might need to just put in so people can see how it actually plays then we can decide to revert or keep later on.
