### ISSUE TITLE
Inventory snaps to top after using a potion

### ISSUE THREAD

**Issue by ArcanumHominem** [MSRevive/MasterSwordRebirth#138]
If you start using a potion or soup then open your inventory and scroll down on one of your bags it will snap back to the top of the bag after the item's animation completes.  Tested on a Bag of Holding while using soup.

**Comment by ArcanumHominem** [comment]
Cancelling a spell will also do this.

**Comment by SaintWish** [comment]
Probably because the GUI is refreshed and when that happens it will reset to the top. Not sure if this is something that can be fixed.

**Comment by SaintWish** [comment]
Closing this for now.
