### ISSUE TITLE
Odd sub-level discrepancy in Spell Casting

### ISSUE THREAD

**Issue by ArcanumHominem** [MSRevive/MasterSwordRebirth#139]
There appears to be a 4 sub-level gap in what is needed for maxing out Spell Casting.  I currently have 45 Spell Casting with 45 Fire, 41 Ice, 45 Lightning, 45 Divination, and 45 Affliction.
![Spell Casting](https://user-images.githubusercontent.com/34590399/213301626-efa2d41c-f8d6-463f-a339-414ed4dd59f9.jpg)

**Comment by SaintWish** [comment]
Fixed by #142
