### ISSUE TITLE
The spawn no-collusion system doesn't activate some triggers.

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#157]
The no-collusion system prevents some triggers from activating on player touch until the player is turned solid again. An example of a trigger broke by this is CAreaMusic. Also when players are non-solid they're unable to targeted with spells, like ice shield.

**Comment by Aze-M** [comment]
As mentioned in the PR:

Triggers now work properly and the system has been made much more aggressive in removing nocollide to make it easier to get collisions back.

The whole Music thing is completely broken, no music ever plays despite the point and the area triggers firing the script event and the scripts firing the associated function internally. Unfortunately I can't get symbols for the Soundengine to debug it's incoming commands, so I have no idea where the failure is.

**Comment by Aze-M** [comment]
![Screenshot 2023-02-12 170325](https://user-images.githubusercontent.com/114273422/218322254-a9c8f388-99b8-44df-a8d7-e446c0820bc6.png)

Bisecting to this commit. Likely a function called outside of our code being hijacked for the music, any commit before this has working sound as tested on this map:
[musictest.zip](https://github.com/MSRevive/MasterSwordRebirth/files/10716520/musictest.zip)

**Comment by BerntA** [comment]
Added back the removed hud music code, music works fine now, the music usermessage is handled there (recv)
