### ISSUE TITLE
Dual wielding is funky

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#168]
Sometimes when trying to use both weapon at the same time the charge timer reset or can misfire without you letting go.

**Comment by Aze-M** [comment]
I couldn't find anything where using both at the same time actually misfired, however using the charge on the offhand always also displays the charge bar for the mainhand weapon even if it is not charging.

Debugging shows that in addition to the offhand weapon which is being given the m_hand position of '0' it is also finding the empty hands at position 2 which then causes it to display both charge bars. Unsure how to fix at this point but I'll look more into it.

**Comment by SaintWish** [comment]
Maybe misfire is the wrong word, but often when I'm using 2 neck hunters charge attack the right hand one will just fire for no apparent reason. 

It might be a script issue as well though, since I believe some parts of the logic are located in via scripts.

**Comment by Aze-M** [comment]
There is #173 now for the ui displaying charge bars that it shouldnt, I still wasn't able to reproduce charge attacks firing without me letting go unfortunately,

I ran circles around chapel while using and charging my main neckhunter to kill things while also holding charge on my offhand neckhunter without the offhand ever firing. Charging them at the same time and only releasing one also never fired the other.

**Comment by SaintWish** [comment]
The random firing was due to my mouse.
