### ISSUE TITLE
Make the character system use JSON for new FN

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#17]
This will be needed to work with via new FN server, this also means get rid of character file encryption which isn't really needed honestly anyways.

Perhaps this would a good thing to use, so we don't have to write our own JSON parser... 
https://github.com/nlohmann/json

**Comment by SaintWish** [comment]
Here's the response structure for the new FN server. We'll also need a library for doing HTTP requests to via new FN server, maybe this would be a good library? https://github.com/libcpr/cpr

Response structure:
```json
{
  "code": <HTTP status code:int>,
  "status": <successful request:bool>,
  "error": <error:string>,
  "data": <data>
}
```

example character structure:
```json
{
  "steamid": "76561198092541770",
  "slot": 2,
  "name": "Test Char",
  "gender": 1,
  "race": 1,
  "flags": "{}",
  "quickslots": "{}",
  "quests": "{}",
  "skills": "{}",
  "pets": "{}",
  "health": 5,
  "mana": 10,
  "equipped": "{}",
  "spells": "{}",
  "spellbook": "{}",
  "bags": "{}",
  "sheaths": "{}"
}
```

**Comment by BerntA** [comment]
integration is complete: additional task would be to make it proper multi-threaded!
