### ISSUE TITLE
XP balancing affects spellcasting when it should not

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MasterSwordRebirth#187]
As an example, if your lowest spell casting level is affliction, no matter which spellcasting weapon you use, it will level affliction, because it is trying to average it out.

**Comment by SaintWish** [comment]
~~Actually after further testing it will always level affliction atleast in my case even when affliction isn't my lowest. Perhaps it's going in ABC order or something?~~ It seems to start leveling your lowest spell casting skill after a little bit.
