### ISSUE TITLE
Music triggers not working consistently

### ISSUE THREAD

**Issue by Dark4557** [MSRevive/MasterSwordRebirth#198]
Music is being odd currently, in that you can touch a trigger on the map to play music, but it's random whether it decides to play the music at that moment or 10 min. later

Great example is Edana where you can spawn in with no music at all, run down to the town and through the music trigger there, and suddenly 5 min. later you get the temple music, not the town music

**Comment by SaintWish** [comment]
_Should_ be fixed, needs further testing to confirm though.
