### ISSUE TITLE
Use Spirinity codebase

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#204]
Might be nice at some point to use Spirinity code base since they've updated their sound engine engine to use FMOD and use all of Trinity Renderer's features.

https://github.com/edgarbarney/halflife-planckepoch

**Comment by thesupersoup** [comment]
FMOD has compatibility issues with Linux even running through Proton, from my experience; just something to consider

**Comment by SaintWish** [comment]
Good to know and consider, might be worth just using OpenAL instead then?

**Comment by thesupersoup** [comment]
Yeah, I do have some experience with OpenAL and Linux. Enough to say "Maybe there's a better option," but maybe the grass is always greener...

It actually works, at least.

**Comment by SaintWish** [comment]
Probably not gonna to happen because currently Spirinity renderer relies on windows.
