### ISSUE TITLE
Scoreboard displays HP incorrectly

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MasterSwordRebirth#208]
"I'm not sure if it just takes a couple seconds to catch up or not. I don't remember if it ever was real-time though

"It never was in real time"

"It updates when a player touches a transition point. I don’t know if we could make it update at intervals and connections instead"

"yeah at some point the way the scoreboard got updated got changed."

**Comment by SaintWish** [comment]
Been meaning to look at that, just haven't had time.

**Comment by Aze-M** [comment]
I'm looking into this currently, do we want the scoreboard to just update everything more consistently than it currently does? It hsould be a rather simple thing by slightly expanding the info in the comparison, such as adding current hp , then following the established way of updating it.

See PR #246

**Comment by SaintWish** [comment]
Fixed in this commit https://github.com/MSRevive/MasterSwordRebirth/commit/a3d8381c03f24986c60a113b76a5585e73aadef8
