### ISSUE TITLE
Add linux compatibility

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#22]
It would be nice to support linux at-least for servers for obvious reasons.

**Comment by BerntA** [comment]
We can refer to the default SDK 2013 "building on Linux" guidelines (thankfully), also it seems like all the static libs are for the client only, seeing as they are either graphics or GUI related, which means we probably only have to fix:
* Make sure that all #include statements have the right casing, perhaps we should just lower case all .cpp / .h filenames in the repo, and includes @ code?
* Linux alternative code for areas where windows headers are used, thankfully not too many places, last time I checked!
* Compile with Steam runtime as explained in [SDK 2013](https://developer.valvesoftware.com/wiki/Source_SDK_2013#Source_SDK_2013_on_Linux) - I can do some testing on my local linux server 
* Add workflow to compile on Linux later, I already have one for BrainBread / Infestus which can be used for this 
* Test with HLDS on linux

**Comment by SaintWish** [comment]
Sounds good, I can run a game server for the game for testing the linux changes on my linux box. I'll make a list of all the files that used windows headers.

**Comment by SaintWish** [comment]
soundsystem.cpp and hudmusic.cpp requires ``windows.h`` and ``mmsystem.h`` for playing MIDI files. Relies on via the mmsystem mci and mdi functions and types for playing MIDI files, which will make it a pain to convert it over to linux.

**Comment by BerntA** [comment]
Is most of this logic client side? We can probably omit client side stuff, as long as we can compile the ms.so (server side part), only this is needed for the dedicated server I suppose.

**Comment by SaintWish** [comment]
Yeah, I was thinking about doing that as well, from the looks of it _might_ compile for linux on server side already. I can't really test currently, but if it doesn't compile we should be super close.

**Comment by BerntA** [comment]
works so far, needs more testing to fix potential exceptions!
