### ISSUE TITLE
setenv sky.texture does not work

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MasterSwordRebirth#235]
when supplied with the name of a sky, it should immediately change the sky texture to the one provided, however, nothing appears to happen.

**Comment by frendship-loost** [comment]
Did you tell the script to manually cache the sky texture you tried to change to? Maybe the engine only caches 1 sky at a time normally.

**Comment by SaintWish** [comment]
All should be done towards Angelscript after next patch.
