### ISSUE TITLE
Rewrite player race system to go by an ID

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#24]
The current player race system uses strings instead of having an ID system, because it would interfere with via monster race system...

**Comment by BerntA** [comment]
legacy characters will have a hard time loading if we change the race stuff to be for ex a 4 byte int or such, since the current header loads 16 bytes for the race name, could keep it a string for compatibility?

**Comment by SaintWish** [comment]
Yeah it might be better to keep it as a string, we'll see when or if we ever get models for other races.
