### ISSUE TITLE
Display scaling in Windows 10/11 breaks MSR

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#245]
When you launch MSR with display scaling turn on anything above 100% it will cause the game to ultra zoom in. 

This isn't an issue with the borderless window system we use or with default HL pre-25th, so it has to be an issue somewhere else in our client code.

A workaround for users who run Windows with display scaling turned up above 100% (most likely laptop users due to laptop's small screen sizes) is to turn on "Override high DPI scaling behavior" and set it to "Application".

Ex. <img width="503" alt="Screenshot 2024-09-13 181853" src="https://github.com/user-attachments/assets/ec3b4915-3abc-4640-b182-a7f7732a39fd">

**Comment by frendship-loost** [comment]
Related to #97

**Comment by SaintWish** [comment]
Duplicate of

**Comment by SaintWish** [comment]
Duplicate of #97, nice catch.
