### ISSUE TITLE
Allow force/deny transmit for NULL models / invalid models

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#27]
Add entity flags that allow force transmit and deny transmit of an entity, even if the model is invalid or valid.
- Verify that this works on the client, are there any engine limitations to doing this? (Source allows this via entity flags)
- Don't transmit model if using null.mdl for ex

**Comment by SaintWish** [comment]
Could we use the built in ``CBaseEntity->(entvars_t)pev->flags`` and add our own flags and then do WRITE_ENTITY for force transmit. 

I don't know how you would prevent the engine from sending entity using a custom flag though, maybe set the engine entity flag of ``FL_DORMANT`` upon entity creation to prevent it from updating the client on?

**Comment by BerntA** [comment]
Yeah the pev->flags seems like the right "place" to put the flags, we can prevent the transmission of the entity entirely / force transmit via the add to packet function in client.cpp, see AddToFullPack.

**Comment by SaintWish** [comment]
I implemented the logic for it in the alpha-scriptcmd branch, it just requires testing to confirm that it works. I didn't know any helper functions for reading or setting the two flags that are added.

Flags:
```
FL_ENTNOSEND - Skips sending entity with this flag to the client.
FL_ENTFORCESEND - Skips the checks on whether a entity should be sent to via client.
```

**Comment by greatguys1** [comment]
Exception for "models/null.mdl" fixed and tested. Scripts with "models/null.mdl" as their model no longer transmit information to the client: https://github.com/MSRevive/MasterSwordRebirth/commit/5db14489d7517b22e5e694411c461290e565165a

Other flags untested.

**Comment by BerntA** [comment]
Need to phase :
- FL_ENTNOSEND
- FL_ENTFORCESEND 
into a different variable, perhaps in baseentity? they are too large

**Comment by SaintWish** [comment]
Added two new script functions.
``$set_ent_forcesend <entity> <bool>`` - Scope: Server, Set the entity to be force sent to the client.
``$set_ent_nosend <entity> <bool>`` - Scope: Server, Set the entity to not be sent to the client.

**Comment by greatguys1** [comment]
Commands were updated, so listing it here:

```
nosend <ent> <bool> 
forcesend <ent> <bool>
```
