### ISSUE TITLE
Exception when allocating memory

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#30]
**Alphacmd branch - SERVER**

Whenever you try to load a on thornlands with ms_dev_mode on it will crash with this spammed in the server log, but it will not crash when ms_dev_mode is turned off. However the crash doesn't happen when there's no scripts in the test_scripts, but memory allocation error will still happen.

Perhaps, the crash is unrelated to the exception and possibly a flag issue, need to check on that.
```
MSMEMORY: Unhandled Exception While Allocating Memory! (*operator new) server
```

**Comment by greatguys1** [comment]
Fixed in https://github.com/MSRevive/MasterSwordRebirth/commit/7cd9c3cef12f1461d9d6591784780994f8ca5435
