### ISSUE TITLE
Check additional FN properties

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#36]
Check this in the game:
- api/v1/ban/{steamid} << can be checked in client.cpp, there is a segment where we store the client IP address and cache the steamID, use this info to also lookup if the steamID is banned, if so, disconnect the player.
-  api/v1/sc/{hash} << can be checked when the game server has loaded, e.g. dll load func in client cpp or other func, print a warning if there is a mismatch, or quit entirely?
- api/v1/map/{name}/{hash} << can be checked on level init on the game server, just print a warning that the map is outdated, and that some players might not be able to join because the steam build uses a newer map or smth?

**Comment by BerntA** [comment]
just need sc hash check

**Comment by SaintWish** [comment]
done
