### ISSUE TITLE
Dont drop players during changelevel

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#46]
Using changelevel in local or on a server works perfectly fine now, we should do so that changelevels will write a usermessage to every player -> to do cleanup, and we unload the players accordingly on the server, block plrs from loading in new characters, then after roughly a second, initiate the changelevel. (print transiting to XYZ on the HUD as well)

**Comment by greatguys1** [comment]
The scripts tells the players to drop.
It executes "recon.cfg" in the game directory. I'll remove this function, then recon.cfg can be safely removed.

**Comment by SaintWish** [comment]
Should be done with https://github.com/MSRevive/MSCScripts/commit/6b9afbfd235fe1aa3689da00d883543dfd0c7563
