### ISSUE TITLE
ENGINE_FORCE_UNMODIFIED doesn't work?

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#49]
https://github.com/MSRevive/MasterSwordRebirth/blob/807efd0d2c04662cba364180b199408b4d940267/game/server/svglobals.cpp#L183 
This is a engine function that does a CRC check against a file to make sure it isn't modified by the client. This is something we should have for sc.dll and client.dll to make sure they match the server's to avoid people from modifying those for cheating purposes.

**Comment by BerntA** [comment]
works for client.dll, verify for sc.dll

**Comment by SaintWish** [comment]
Just verified, doesn't work with sc.dll
