### ISSUE TITLE
crashed.cfg is filled with junk on Linux

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#52]

**Comment by SaintWish** [comment]
Log files are also filled with some weird stuff on linux aswell. (log_msdll.log)

**Comment by SaintWish** [comment]
Might have been caused by the ofstream not being flushed, atleast according to this https://stackoverflow.com/q/45085960

Might be solved with new logger, but needs testing on linux.

**Comment by BerntA** [comment]
nice, will check

**Comment by BerntA** [comment]
works
