### ISSUE TITLE
Contact Valve to settle AppID issues

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#53]
Created support ticket(s) to request help with updating the engine to reflect MS:R appid..

**Comment by BerntA** [comment]
No luck yet -best bet is to use steam API to fetch the server list in a new server browser GUI from scratch, this is fairly simple to add anyways..

**Comment by SaintWish** [comment]
Maybe we can rewrite getting the server list to use the Steamworks API instead, though I don't know if this is even used or was it switched over to the engine side? https://github.com/MSRevive/MasterSwordRebirth/blob/3fcfb8e1bae0e3a511476fa9148197d68915eca7/game/client/hud_servers.cpp

**Comment by BerntA** [comment]
Yeah, I added the missing steam API headers and ensured we actually load it client/server side, so yeah we can use that to query the correct appid for servers, just gotta hook it up to show the menu in the main menu, and it would be nice to hide the "Server" button on the right side above the steam icon though, since this opens the old browser :|

**Comment by BerntA** [comment]
This has finally been sorted!
