### ISSUE TITLE
CTD casued by DLL mismatch

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MasterSwordRebirth#56]
First time doing something like this:

Crash to desktop after changing resolution between aspect ratios.

Recreation method:

Edited config.cfg, appending "default_fov 130" and "cam_idealdist 120" at second-to-last line. (https://gyazo.com/85747f4cb9db652b768b3ea27af4fb33)

Started game in 21:9, 2560x1080 resolution (https://steamuserimages-a.akamaihd.net/ugc/1844796405265900942/EE56C4805EB3F4FB7B45CDD1B9A0B2F191CC8D6A/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false) on Edana.

Changed resolution from 2560x1080 to 1920x1080. Game closes as normal. Relaunch the game and start a new map on Edana again, only to have the listen server hang on "Creating local server..." then crashes to desktop with this error: https://gyazo.com/72601d057fa388e5466722f14db85b0f

After which, the config.cfg has been reverted to default as well.

**Comment by BerntA** [comment]
can you try again with the latest build?

**Comment by Drathamus** [comment]
Seems to work perfectly fine when connecting to the test server. But when attempting a listen server, it still crashes after startup from changing resolutions.
