### ISSUE TITLE
Could not load library client.dll

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#60]
Age is having this issue even after verifying his game files through Steam. Apparently, the issue happened in MSC as well but somehow he got it fixed, here's everything he did to fix it on MSC.

https://cdn.discordapp.com/attachments/966184633492467772/975837240141971496/unknown.png

**Comment by BerntA** [comment]
I had the same issue, just using the installer solved it for me as well..

**Comment by BerntA** [comment]
Solved: cg programs dll files had to be put in the root dir!
