### ISSUE TITLE
m2_quest not tracking objectives

### ISSUE THREAD

**Issue by Drathamus** [MSRevive/MasterSwordRebirth#61]
As title states, m2_quest is not tracking quest objectives. Sylphiel's quest bugs out after gathering one golden apple, and none of the other collectibles count toward the quest completion.

**Comment by SaintWish** [comment]
Sounds like a script issue, I'll let @greatguys1 confirm if it is.

**Comment by greatguys1** [comment]
This is a script issue. Moving the issue here: https://github.com/MSRevive/MSCScripts/issues/31
