### ISSUE TITLE
Suggestion: Summoned Allies That Kill Monsters Should Grant the Player Experience Towards Divination

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#68]
I think this suggestion is overdue, and has been overdue for years now:
- Summoned allies that kill monsters should grant the player experience towards divination.

I'm not quite sure why this has never been implemented, but the summonable allies and monsters of MS:C have always been pretty bad, nor does anyone really use them often aside for a couple specific sections of the game. Allowing "Summon Rat" to grant rats that actually give the player experience towards Divination would be an early game-changer. Needless to say, there must be a reason why it hasn't been implemented, and if it is for balance reasons, how would we balance something like that?

**Comment by greatguys1** [comment]
Im not really sure if summoning skeletons would really be considered "divine". Either way it should grant xp towards _something_.
I'm also not sure if there's a function that allows monsters to redirect xp. But I'd have to see what I could do.

**Comment by RWGryphon** [comment]
> Im not really sure if summoning skeletons would really be considered "divine". Either way it should grant xp towards _something_. I'm also not sure if there's a function that allows monsters to redirect xp. But I'd have to see what I could do.

For simplicity's sake, and for the overall scaling of summoned monsters, we understand that a higher divination level = better summon. I think we should keep it in the game just for simplicity's sake, similar to how MS:C got rid of other schools of spells for similar reasons.

**Comment by PHILLIPGATLIN** [comment]
I want to suggest the idea that summoned allies that kill monsters rewards the player with generic spell casting experience that is equally distributed to all spell casting sub-skills rounded down.
