### ISSUE TITLE
Having ms_dev_mode set to 1 crashes the game on map start

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MasterSwordRebirth#78]

**Comment by SaintWish** [comment]
I set it in the console then votemap to edana and it froze my server (Linux US Central) with this in the console...
```
src/tier1/fileio.cpp (5125) : m_vecRegisteredWriters.Count() == 0
src/tier1/fileio.cpp (5125) : m_vecRegisteredWriters.Count() == 0
```

**Comment by SaintWish** [comment]
With rehlds this causes server to on changelevel and startup with this error 
```
free(): double free detected in tcache 2
```

**Comment by SaintWish** [comment]
Will probably rewrite this or get rid of it once the new script system is embedded.
