### ISSUE TITLE
Skycastle considers most players illegal.

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#82]
No idea why this happens but skycastle has a tendency to be a nuisance when loading, considering legal players illegal.
Again, I don't know why this happens but it seems to happen often.

**Comment by BerntA** [comment]
I think it may be a save issue, perhaps characters are not saved properly before the level change ?

**Comment by greatguys1** [comment]
I think this is a script issue. I believe it has to do with case sensitivity in the gauntlet map system. I'll look into it
