### ISSUE TITLE
What's Up With the Crouching?

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#84]
MS:R's crouching (and MSC in general) is slow and sluggish, which is something that doesn't exist in all the other half life games and mods. Why? 

Is this a bug that can be fixed? Just posting it here to remind everyone.

**Comment by greatguys1** [comment]
It feels a little slow, especially with high weight. Actually, with high weight, its hard to get through any tunnels without jumping through or holding down the sprint key. It probably could be sped up just a little bit.

**Comment by RWGryphon** [comment]
But doesn't it feel laggy in a way? I really don't remember other half-life mods acting this way.
When you crouch and move around as a client, you slip-and-slide in a way. It doesn't track normally...
It's hard to explain.

**Comment by SaintWish** [comment]
> But doesn't it feel laggy in a way? I really don't remember other half-life mods acting this way. When you crouch and move around as a client, you slip-and-slide in a way. It doesn't track normally... It's hard to explain.

The slip and sliding thing sounds like a physics engine problem, I remember the same issue happening on source mods when you were crouch moving on something other than a brush.

**Comment by greatguys1** [comment]
Yes it does feel laggy. I think it has something to do with the engine's stuck checks, because it can happen when you hold crouch, and in some cases attack, which invokes some stuck checks. I might be able to get a video demonstrating it.

**Comment by greatguys1** [comment]
PM_CheckStuck() contribues to this issue. Commenting it out subsided jittering in multiplayer while crouched.
