### ISSUE TITLE
"Break into a jog." Message should maybe be removed?

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#85]
I understand it's always been a part of the charm, but it does result in problems like this:

![image](https://user-images.githubusercontent.com/57601165/177238324-6644625d-0021-4eb3-8c63-24538825ea9c.png)

**Comment by greatguys1** [comment]
I quite like the flavor text, and I would advocate for more things like that. I dont think it gets in the way while action is going on.

**Comment by RWGryphon** [comment]
Then as a compromise, perhaps an option could be made to disable that text?
If not, it isn't a huge problem either.

**Comment by greatguys1** [comment]
Options benefit everyone, it would be possible to add a console variable that disables flavor text in the battle log.

**Comment by RWGryphon** [comment]
Thank you. :>

**Comment by BerntA** [comment]
more options to add/remove stuff to the "event/combat" log would be nice !

**Comment by SaintWish** [comment]
Done by @Aze-M

> Added CVAR ms_sprint_verbose with multiple levels:
> "0" will result in neither sprint warnings (stamina etc.) nor sprint messages ("You break into a jog") being printed.
> "1" will print warnings but not messages.
> "2" (Default setting) will print everything.
