### ISSUE TITLE
Removing Container Items and Dropping Them After Acquiring a New Item In Them Too Quicky RESULTS IN THE ITEM BEING LOST.

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#86]
Apparently when you place items in a bag quickly and drop them, you will lose the items inside that you've recently acquired...

Does this have to do with character data updates?

**Comment by greatguys1** [comment]
I can't reproduce this. Are you able to replicate it and explain the process?

**Comment by RWGryphon** [comment]
This issue may be more related to player exchange as Rust took several items I gave him, dropped his container (backpack) and picked it up only to see his items were lost. 

Can test tomorrow.

**Comment by greatguys1** [comment]
I believe that's related to an item ownership bug. If you pass a player items, they must hold it in their hands to claim "ownership" of it. If they don't, and the original owner leaves, the item disappears. Could that have happened? I will also create that as an issue.

**Comment by RWGryphon** [comment]
I don’t believe so as he dropped the items and picked them up. The game didn’t say they were mine. They were “supposedly” his.
It’s very confusing to me…

**Comment by greatguys1** [comment]
I see. Hopefully there will be a reliable way to reproduce this so we can find out what's happening.

**Comment by greatguys1** [comment]
Sorry for all the questioning, but did he happen to use "vanish all" to unsummon friendies around the time he dropped it?

**Comment by RWGryphon** [comment]
No friendly summons were in use at this time.

**Comment by SaintWish** [comment]
Probably fixed with this https://github.com/MSRevive/MasterSwordRebirth/commit/3ce1b0c9d08b4db24c13aedc8369f7a0379c529c
