### ISSUE TITLE
More sorting options for the inventory

### ISSUE THREAD

**Issue by greatguys1** [MSRevive/MasterSwordRebirth#88]
The inventory would benefit from sorting options in the UI. Sorted items would display only items of a specific item class (potions, 1-handed, Swords, Spells, etc.).
How it's incorporated in the UI is important, it should be easy to understand and intuitive. We may need a UI overhaul before doing something like this. It really depends. I'll passively think of designs but this is low priority.

**Comment by SaintWish** [comment]
Closing in favour of this issue https://github.com/MSRevive/MasterSwordRebirth/issues/181
