### ISSUE TITLE
Monster Health Display Concerns

### ISSUE THREAD

**Issue by Charles445** [MSRevive/MasterSwordRebirth#90]
It looks like the bloodstone ring is planned to be changed, and health indicators are now in the bottom left.
While it's really nice to have specific numbers available, there's a couple of issues with it when compared to health bars.

1. It's much harder to gauge how overall healthy a monster is (125/500 is harder to understand than a visual fourth of a health bar)
2. Instead of the information being presented where the player is looking (center of the screen at the monster), it's down and to the left

There's a few issues with the current implementation as well:
1. The health display disappears before the monster is dead, if their health is below 1 (might as well just display 1 or 0 here)
2. The health display shows up on friendly NPCs that have full health, and feels tonally out of place

It would be nice to be able to toggle the old health bars, that way there would be quick information at a glance, and anyone looking for more information could always look at the new text readout.

**Comment by greatguys1** [comment]
I agree with a lot of the points here. I think the numerical display is better for me to read though, so there should be an option for an alternative.
I think it would be neat if the enemy you most recently attacked had their health displayed in a numerical value, but enemies that you had hit prior have just their health bars displayed.

**Comment by Dark4557** [comment]
I'm gonna propose a thing that can be there in conjunction with the numerical health indicator, but wanna hear more people's thoughts on it.

Down where the name is displayed of the mob you're looking at, it'll say "Friendly" or "Hostile" with green or red text, either replace or add next to it a text based health bar that changes colour and text, depending on the % health of the mob, something like: 

```
>Healthy -Green 81-100% HP
>Hurt -Slightly yellow Green 80-61% HP
>Wounded -Yellow 60-41% HP
>Badly Wounded -Orange 40-21% HP 
>Near Death -Red 20-0% HP

**Comment by greatguys1** [comment]
> I'm gonna propose a thing that can be there in conjunction with the numerical health indicator, but wanna hear more people's thoughts on it.
> 
> Down where the name is displayed of the mob you're looking at, it'll say "Friendly" or "Hostile" with green or red text, either replace or add next to it a text based health bar that changes colour and text, depending on the % health of the mob, something like:
> 
> ```
> >Healthy -Green 81-100% HP
> >Hurt -Slightly yellow Green 80-61% HP
> >Wounded -Yellow 60-41% HP
> >Badly Wounded -Orange 40-21% HP 
> >Near Death -Red 20-0% HP
> ```

I like it, I feel like it adds some flavor, & can be used for friendly npcs too for flavor in cutscenes. I feel like it can safely replace the "Friendly" or "Hostile" text, as its relatively easy to determine if something is hostile to you. 

I think this would be good in addition to what I recommended earlier.

Maybe this should not show if an npc is invulnerable though. It might be weird seeing "Healthy" on every shop npc you come across.

**Comment by Aze-M** [comment]
I'll try implementing some form of toggleable coloring for the health display as well as moving the looking at infor closer to center of screen.
