### ISSUE TITLE
Improve crashed.cfg logic

### ISSUE THREAD

**Issue by BerntA** [MSRevive/MasterSwordRebirth#93]
As requested by Age, allow servers to write/load to a specific "crashed.cfg" file, if you run multiple servers and two of them crashes on different maps, the server which loaded the crashed map first will be the map to load for both servers on restart..

**Comment by SaintWish** [comment]
Done with this https://github.com/MSRevive/MSCScripts/commit/87b226f4aeb297ce530752485c91847f3c6c2438
