### ISSUE TITLE
Graphical issue with character select on some maps

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#95]
![unknown-1.png](https://user-images.githubusercontent.com/6036821/194237607-4b361227-2641-41bd-8493-fe7e2ab5e7a0.png)
Some maps seem to cause the character select screen to have a graphical glitch, so far only the_keep is confirmed but pretty sure I experienced this issue on other maps as well.

**Comment by BerntA** [comment]
this happens in source engine maps when you spawn outside the skybox / no skybox nearby, not sure if it would be something similar here? Do you spawn in an actual spawn point before the selection is made? or is your view changed to (0,0,0) etc?

**Comment by SaintWish** [comment]
I was thinking the same thing I'll try to go through the code for it and see how it works.

**Comment by frendship-loost** [comment]
Slightly different but related to this issue:

![image](https://user-images.githubusercontent.com/85242183/194699512-98400be2-7dbd-4f33-a689-e17476687ced.png)


Sometimes on map load into character select, your previews will have very strange coloring on the armors, wrong crest textures, seems to be scrambled texture data. Happens pretty frequently after a few map changes without restarting the game, but not always.
**EDIT: I can confirm it also happens at first-time load. Launched MS Rebirth from steam, loaded into Edana and got this bug right away.

**Comment by SaintWish** [comment]
The game uses the ``ms_player_spec`` entity within the map (somehow since I never found the code to reference this) and the_keep just had a badly placed one, if a map doesn't have one then it defaults to a black background. Though it worked in MSClassic because there's was broken while MSR magically fixed it I guess...
